# Generated by Django 4.2.2 on 2023-07-02 22:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('df0954c5-8571-43c3-a61b-b6c63f39addc'))),
                ('address', models.TextField()),
                ('social_media_info', models.JSONField()),
                ('band_photo_url', models.URLField()),
                ('band_logo_url', models.URLField()),
                ('band_bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('94156589-b6ef-4c66-abf9-a41c34d6b2e3'))),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('bands', models.ManyToManyField(to='api.band')),
            ],
        ),
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('e2769414-e821-4a2b-a610-67b79c2eb75c'))),
                ('bridge_flag', models.BooleanField(default=True)),
                ('contest_flag', models.BooleanField(default=True)),
                ('general_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('6f851974-40f2-4dbd-ba8e-79cfff85e6d7'))),
                ('master_start_time', models.DateTimeField()),
                ('master_end_time', models.DateTimeField()),
                ('performance_time', models.DateTimeField()),
                ('slot_anonymizing_slug', models.TextField()),
                ('streaming_links', models.JSONField()),
                ('warmup_location', models.TextField()),
                ('case_storage', models.TextField()),
                ('warmup_time', models.DateTimeField()),
                ('photo_time', models.DateTimeField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.band')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.contest')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('73964df1-9b15-482b-be93-4adbc98ea8d0'))),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip', models.TextField()),
                ('country', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('youth', models.BooleanField()),
                ('headshot_url', models.URLField()),
                ('social_media_info', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('fa0c8de1-5f89-4b8f-b2c9-bb7cc2645e50'))),
                ('name', models.TextField()),
                ('abbreviation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('bc098aa8-49be-4906-8848-46d8fb76f585'))),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('venue_information', models.TextField()),
                ('map_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('5266708a-38f7-41d7-9bf2-e1bcce5ab57b'))),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.contest')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.person')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.performanceslot')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('aa5d5b50-b0d4-4556-9f5c-07722dc25715'))),
                ('score_sheet_url', models.URLField()),
                ('score', models.FloatField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.band')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.contest')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('f373ffdb-c69c-4f3e-9ce6-99f6c3cc602d'))),
                ('stripe_uuid', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('is_subscription', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.person')),
            ],
        ),
        migrations.AddField(
            model_name='performanceslot',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.person'),
        ),
        migrations.AddField(
            model_name='performanceslot',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.venue'),
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('6a8ee5a6-43aa-47e9-9224-b6f29cc9d4a7'))),
                ('instrument', models.TextField()),
                ('bands', models.ManyToManyField(to='api.band')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('b2d26b59-87cd-47d2-a78a-7797f4ff6aa6'))),
                ('is_test_piece', models.BooleanField(default=False)),
                ('publisher', models.TextField()),
                ('title', models.TextField()),
                ('composer', models.TextField()),
                ('performance_length', models.TextField()),
                ('reference_recording_url', models.URLField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.section')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('ecb946d4-6c5b-45ba-bc32-b5015aa36633'))),
                ('bio', models.TextField()),
                ('headshot_url', models.URLField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.person')),
                ('slots', models.ManyToManyField(to='api.performanceslot')),
            ],
        ),
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('5d3bceae-0166-4319-bafc-0c70d830d710'))),
                ('name', models.TextField()),
                ('members', models.ManyToManyField(to='api.musician')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('9b187963-979a-4557-bdb3-3a6f4632a7fe'))),
                ('bio', models.TextField()),
                ('bands', models.ManyToManyField(to='api.band')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('b80a5d57-9e8e-446a-87ba-6e33f8745ac3'))),
                ('commentary_url', models.URLField()),
                ('performance_slot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.performanceslot')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.person'),
        ),
        migrations.AddField(
            model_name='band',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.section'),
        ),
    ]
