# Generated by Django 3.1 on 2023-09-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230929_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
