# Generated by Django 4.2.2 on 2024-01-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_band_id_alter_commentary_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceslot',
            name='performance_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='performanceslot',
            name='stage',
            field=models.TextField(null=True),
        ),
    ]
