# Generated by Django 4.2.2 on 2024-01-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_performanceslot_performance_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceslot',
            name='music',
            field=models.ManyToManyField(to='api.music'),
        ),
    ]
