# Generated by Django 5.0.2 on 2024-02-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_performanceslot_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceslot',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='performanceslot',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
