# Generated by Django 5.0.2 on 2024-02-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_performanceslot_description_performanceslot_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceslot',
            name='slot_image',
            field=models.URLField(null=True),
        ),
    ]
