# Generated by Django 5.0.2 on 2024-02-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_performanceslot_slot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceslot',
            name='music',
            field=models.ManyToManyField(null=True, to='api.music'),
        ),
    ]
