# Generated by Django 4.2.2 on 2024-03-01 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_performanceslot_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.venue'),
        ),
    ]
