# Generated by Django 4.2.2 on 2024-03-01 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contest_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.URLField(null=True)),
                ('name', models.TextField(null=True)),
                ('link', models.URLField(null=True)),
                ('background', models.TextField(null=True)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.contest')),
            ],
        ),
    ]
