# Generated by Django 4.2.2 on 2024-03-01 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
