# Generated by Django 4.2.2 on 2024-03-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_partner_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
