# Generated by Django 4.2.2 on 2024-03-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_venue_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
