# Generated by Django 4.2.2 on 2024-03-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_venue_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='venue',
        ),
        migrations.AddField(
            model_name='contest',
            name='judge_bio_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='solo_ensemble_link',
            field=models.URLField(null=True),
        ),
    ]
