# Generated by Django 5.0.2 on 2024-03-01 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_contest_venue_contest_judge_bio_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.venue'),
        ),
    ]
